// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJlrAW77pD-boqFpDXC8jyMV6zZLuvWws',
    appId: '1:999391457331:web:3b8d8545eff352a8397346',
    messagingSenderId: '999391457331',
    projectId: 'chat-d06f8',
    authDomain: 'chat-d06f8.firebaseapp.com',
    storageBucket: 'chat-d06f8.firebasestorage.app',
    measurementId: 'G-GRJKQ1GH0H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-mreiNfa0SkY9XKTdLGfTxBbHW-k0Fx8',
    appId: '1:999391457331:android:67d36b5fd3764629397346',
    messagingSenderId: '999391457331',
    projectId: 'chat-d06f8',
    storageBucket: 'chat-d06f8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZDd80V60WwdnMqRQtdIBkXZVzSb2RFCc',
    appId: '1:999391457331:ios:d1c7a3ce3ec373da397346',
    messagingSenderId: '999391457331',
    projectId: 'chat-d06f8',
    storageBucket: 'chat-d06f8.firebasestorage.app',
    iosBundleId: 'com.example.flutterLearn',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZDd80V60WwdnMqRQtdIBkXZVzSb2RFCc',
    appId: '1:999391457331:ios:d1c7a3ce3ec373da397346',
    messagingSenderId: '999391457331',
    projectId: 'chat-d06f8',
    storageBucket: 'chat-d06f8.firebasestorage.app',
    iosBundleId: 'com.example.flutterLearn',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDJlrAW77pD-boqFpDXC8jyMV6zZLuvWws',
    appId: '1:999391457331:web:a851bb44099e28ae397346',
    messagingSenderId: '999391457331',
    projectId: 'chat-d06f8',
    authDomain: 'chat-d06f8.firebaseapp.com',
    storageBucket: 'chat-d06f8.firebasestorage.app',
    measurementId: 'G-SEQ2GZ2Y0X',
  );
}
